stages:
  - build

build:
  stage: build
  image: maven:3.6.3-jdk-8
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
    MAVEN_DEPENDENCIES_URL: https://github.com/xuxiaowei-com-cn/maven-dependencies/releases/download/v0.0.0-2024-02-29T02-05Z/maven-dependencies-linux-amd64
  script:
    - GPG_FILE=`find / -name xuxiaowei_0x30F97859_SECRET`
    - echo $GPG_FILE
    - gpg --import $GPG_FILE
    #- SETTINGS_FILE=`find / -name settings.xml`
    #- echo $SETTINGS_FILE
    - SETTINGS_FILE=/usr/share/maven/conf/settings.xml
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" $SETTINGS_FILE
    - VERSION=2.3.0-SNAPSHOT
    - echo $VERSION
    - NACOS_TAG_VERSION=$(echo $VERSION | sed 's/-SNAPSHOT//')
    - echo $NACOS_TAG_VERSION
    - git clone --depth 1 --branch $NACOS_TAG_VERSION https://github.com/alibaba/nacos.git
    - echo $MAVEN_DEPENDENCIES_URL
    - wget $MAVEN_DEPENDENCIES_URL
    - chmod +x maven-dependencies-linux-amd64
    - sed -i '\#<artifactId>nacos-config</artifactId>#i\<groupId>io.xuxiaowei.nacos</groupId>' $CI_PROJECT_DIR/nacos/config/pom.xml
    - $CI_PROJECT_DIR/maven-dependencies-linux-amd64 dependency edit --file-path=$CI_PROJECT_DIR/nacos/config/pom.xml                                         --group-id="\${project.groupId}"  --artifact-id=nacos-api                 --after-group-id=com.alibaba.nacos  --after-version=$NACOS_TAG_VERSION
    - $CI_PROJECT_DIR/maven-dependencies-linux-amd64 dependency edit --file-path=$CI_PROJECT_DIR/nacos/config/pom.xml                                         --group-id="\${project.groupId}"  --artifact-id=nacos-core                --after-group-id=com.alibaba.nacos  --after-version=$NACOS_TAG_VERSION
    - $CI_PROJECT_DIR/maven-dependencies-linux-amd64 dependency edit --file-path=$CI_PROJECT_DIR/nacos/config/pom.xml                                         --group-id=com.alibaba.nacos      --artifact-id=nacos-encryption-plugin   --after-group-id=com.alibaba.nacos  --after-version=$NACOS_TAG_VERSION
    - $CI_PROJECT_DIR/maven-dependencies-linux-amd64 dependency edit --file-path=$CI_PROJECT_DIR/nacos/plugin-default-impl/nacos-default-auth-plugin/pom.xml  --group-id=com.alibaba.nacos      --artifact-id=nacos-config              --after-group-id=io.xuxiaowei.nacos --after-version=$NACOS_TAG_VERSION
    - $CI_PROJECT_DIR/maven-dependencies-linux-amd64 dependency edit --file-path=$CI_PROJECT_DIR/nacos/istio/pom.xml                                          --group-id="\${project.groupId}"  --artifact-id=nacos-config              --after-group-id=io.xuxiaowei.nacos --after-version=$NACOS_TAG_VERSION
    - $CI_PROJECT_DIR/maven-dependencies-linux-amd64 dependency edit --file-path=$CI_PROJECT_DIR/nacos/console/pom.xml                                        --group-id="\${project.groupId}"  --artifact-id=nacos-config              --after-group-id=io.xuxiaowei.nacos --after-version=$NACOS_TAG_VERSION
    - cd nacos
    - mvn clean install -DskipTests=true
    - rm -rf $CI_PROJECT_DIR/.m2/repository/com/alibaba/nacos
    - rm -rf $CI_PROJECT_DIR/.m2/repository/io/xuxiaowei/nacos
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
